## Script to compare results produced by this package 
## to the results obtained with the authors' code

## requires having run 
## * run_authorscode.R
## * run_gibbs.R

## so that RData files are available in the working directory

## this script just does some plots to make sure the samplers mostly agree

rm(list = ls())
set.seed(1)
library(couplingdeduplication)
## load packages
library(ggplot2)
## set graphical themes
theme_set(theme_minimal())

## update only of N and eta
## load files generated by other scripts
load("gibbs_update_eta_N.RData")
g_nmcmc <- length(gibbs_runs[[1]]$ksize_history)
g_mcmc_subset <- floor(seq(from = g_nmcmc/10, to = g_nmcmc, length.out = 1e3))
load("authorcode_eta_N.RData")
a_nmcmc <- length(authors_runs[[1]]$NZ1)
a_mcmc_subset <- floor(seq(from = a_nmcmc/10, to = a_nmcmc, length.out = 1e3))

## size of the partition, i.e. number of non-empty clusters
matplot(g_mcmc_subset, lapply(gibbs_runs, function(x) x$ksize_history[g_mcmc_subset]) %>% bind_cols(), type = 'l')
matplot(x = a_mcmc_subset, y = lapply(authors_runs, function(x) x$NZ1[a_mcmc_subset]) %>% bind_cols(), type = 'l')
authors_ksize <- unlist(lapply(authors_runs, function(x) x$NZ1[100:a_nmcmc]))
round(table(authors_ksize) / length(authors_ksize),3)
# 
own_ksize <- unlist(lapply(gibbs_runs, function(x) x$ksize_history[100:g_nmcmc]))
round(table(own_ksize) / length(own_ksize), 3)
hist(authors_ksize, prob = T)
hist(own_ksize, prob = T, add = T, col = rgb(1,0,0,0.5))

## N 
matplot(lapply(gibbs_runs, function(x) x$N_history[g_mcmc_subset]) %>% bind_cols(), type = 'l', ylim = c(1500,4e3))
matplot(lapply(authors_runs, function(x) x$Npop[a_mcmc_subset]) %>% bind_cols(), type = 'l', ylim = c(1500,4e3))

## comparison of the number N
authors_N <- unlist(lapply(authors_runs, function(x) x$Npop[100:a_nmcmc]))
own_N <- unlist(lapply(gibbs_runs, function(x) x$N_history[100:g_nmcmc]))
hist(authors_N, prob = T, nclass = 30)
hist(own_N, prob = T, add = T, col = rgb(1,0,0,0.5), nclass = 30)


## update only of N, theta and eta
## load files generated by other scripts
load("gibbs_update_eta_theta_N.RData")
g_nmcmc <- length(gibbs_runs[[1]]$ksize_history)
g_mcmc_subset <- floor(seq(from = g_nmcmc/10, to = g_nmcmc, length.out = 1e3))
load("authorcode_eta_theta_N.RData")
a_nmcmc <- length(authors_runs[[1]]$NZ1)
a_mcmc_subset <- floor(seq(from = a_nmcmc/10, to = a_nmcmc, length.out = 1e3))

## size of the partition, i.e. number of non-empty clusters
matplot(g_mcmc_subset, lapply(gibbs_runs, function(x) x$ksize_history[g_mcmc_subset]) %>% bind_cols(), type = 'l')
matplot(x = a_mcmc_subset, y = lapply(authors_runs, function(x) x$NZ1[a_mcmc_subset]) %>% bind_cols(), type = 'l')
authors_ksize <- unlist(lapply(authors_runs, function(x) x$NZ1[100:a_nmcmc]))
round(table(authors_ksize) / length(authors_ksize),3)
# 
own_ksize <- unlist(lapply(gibbs_runs, function(x) x$ksize_history[100:g_nmcmc]))
round(table(own_ksize) / length(own_ksize), 3)
hist(authors_ksize, prob = T)
hist(own_ksize, prob = T, add = T, col = rgb(1,0,0,0.5))

## N 
matplot(lapply(gibbs_runs, function(x) x$N_history[g_mcmc_subset]) %>% bind_cols(), type = 'l', ylim = c(1500,4e3))
matplot(lapply(authors_runs, function(x) x$Npop[a_mcmc_subset]) %>% bind_cols(), type = 'l', ylim = c(1500,4e3))

## comparison of the number N
authors_N <- unlist(lapply(authors_runs, function(x) x$Npop[100:a_nmcmc]))
own_N <- unlist(lapply(gibbs_runs, function(x) x$N_history[100:g_nmcmc]))
hist(authors_N, prob = T, nclass = 30)
hist(own_N, prob = T, add = T, col = rgb(1,0,0,0.5), nclass = 30)

##
authors_theta11 <- unlist(lapply(authors_runs, function(x) x$theta[100:a_nmcmc,1]))
plot(authors_theta11, type = 'l')
own_theta11 <- unlist(lapply(gibbs_runs, function(x) x$theta_history[[1]][100:g_nmcmc,1]))
plot(own_theta11, type = 'l')
# 
hist(authors_theta11, prob = T, nclass = 50)
hist(own_theta11, prob = T, add = T, col = rgb(1,0,0,0.5), nclass = 50)

authors_theta12 <- unlist(lapply(authors_runs, function(x) x$theta[100:a_nmcmc,2]))
plot(authors_theta12, type = 'l')
own_theta12 <- unlist(lapply(gibbs_runs, function(x) x$theta_history[[1]][100:g_nmcmc,2]))
plot(own_theta12, type = 'l')
# 
hist(authors_theta12, prob = T, nclass = 30)
hist(own_theta12, prob = T, add = T, col = rgb(1,0,0,0.5), nclass = 40)

